// $STAG trivia question bank (85). Cards pre-rendered at assets/trivia/tNN.jpg (NN = index+1).
export const TRIVIA = [
  {"q": "$STAG's mascot is a stag styled after which folk hero?", "A": "William Tell", "B": "King Arthur", "C": "Zorro", "D": "Robin Hood", "answer": "D", "cat": "STAG"},
  {"q": "Which chain did $STAG launch on?", "A": "Tron", "B": "Base", "C": "Robinhood Chain", "D": "Solana", "answer": "C", "cat": "STAG"},
  {"q": "Robinhood Chain is built on which L2 tech?", "A": "Optimism", "B": "Polygon PoS", "C": "zkSync", "D": "Arbitrum Orbit", "answer": "D", "cat": "STAG"},
  {"q": "$STAG's motto: \"Steal the pump, feed the ___\"", "A": "whales", "B": "devs", "C": "holders", "D": "bears", "answer": "C", "cat": "STAG"},
  {"q": "What is $STAG's total supply?", "A": "100 million", "B": "21 million", "C": "1 trillion", "D": "1 billion", "answer": "D", "cat": "STAG"},
  {"q": "What is the gas token on Robinhood Chain?", "A": "HOOD", "B": "MATIC", "C": "SOL", "D": "ETH", "answer": "D", "cat": "STAG"},
  {"q": "Which launchpad was $STAG created through?", "A": "Raydium", "B": "Pump.fun", "C": "NOXA Fun", "D": "LetsBonk", "answer": "C", "cat": "STAG"},
  {"q": "The @STAGZBOT can generate all of these EXCEPT:", "A": "PFPs", "B": "Short videos", "C": "Your taxes", "D": "Scene images", "answer": "C", "cat": "STAG"},
  {"q": "What is Robinhood Chain's chain ID?", "A": "4663", "B": "8453", "C": "1", "D": "42161", "answer": "A", "cat": "STAG"},
  {"q": "Robinhood is best known as a...", "A": "Social network", "B": "Ride app", "C": "Stock trading app", "D": "Search engine", "answer": "C", "cat": "STAG"},
  {"q": "Which @STAGZBOT command makes a video?", "A": "/image", "B": "/pfp", "C": "/buy", "D": "/vid", "answer": "D", "cat": "STAG"},
  {"q": "Hold how much $STAG to unlock 50% off credits?", "A": "1 billion", "B": "10,000", "C": "100", "D": "1,000,000", "answer": "D", "cat": "STAG"},
  {"q": "Robin Hood famously steals from the rich to give to the...", "A": "banks", "B": "king", "C": "poor", "D": "sheriff", "answer": "C", "cat": "STAG"},
  {"q": "What color glow is $STAG's brand?", "A": "Red", "B": "Gold", "C": "Purple", "D": "Green", "answer": "D", "cat": "STAG"},
  {"q": "Robinhood Chain transactions are cheap because it's a...", "A": "Layer 2", "B": "Layer 1", "C": "Testnet", "D": "Sidechain DB", "answer": "A", "cat": "STAG"},
  {"q": "$STAG's weekly trivia champ wins a prize in...", "A": "Gift cards", "B": "AI credits", "C": "NFTs", "D": "Cash", "answer": "B", "cat": "STAG"},
  {"q": "Where does the term \"HODL\" come from?", "A": "An acronym", "B": "Satoshi's blog", "C": "A Greek word", "D": "A typo of 'hold'", "answer": "D", "cat": "CRYPTO"},
  {"q": "Who is Bitcoin's pseudonymous creator?", "A": "Vitalik Buterin", "B": "Nick Szabo", "C": "Satoshi Nakamoto", "D": "Charlie Lee", "answer": "C", "cat": "CRYPTO"},
  {"q": "What is the max supply of Bitcoin?", "A": "1 billion", "B": "Unlimited", "C": "100 million", "D": "21 million", "answer": "D", "cat": "CRYPTO"},
  {"q": "Who created Ethereum?", "A": "Vitalik Buterin", "B": "Satoshi Nakamoto", "C": "Gavin Wood", "D": "CZ", "answer": "A", "cat": "CRYPTO"},
  {"q": "\"Diamond hands\" means you...", "A": "Hold through volatility", "B": "Day trade", "C": "Short the market", "D": "Panic sell", "answer": "A", "cat": "CRYPTO"},
  {"q": "A \"rug pull\" is when...", "A": "Devs drain the liquidity", "B": "The chart goes up", "C": "A whale buys", "D": "Price 2x's", "answer": "A", "cat": "CRYPTO"},
  {"q": "What does DEX stand for?", "A": "Digital Exchange", "B": "Data Exchange", "C": "Direct Exchange", "D": "Decentralized Exchange", "answer": "D", "cat": "CRYPTO"},
  {"q": "In crypto, a \"whale\" is...", "A": "A dead coin", "B": "An exchange", "C": "A large holder", "D": "A scam token", "answer": "C", "cat": "CRYPTO"},
  {"q": "\"WAGMI\" stands for...", "A": "Whales Always Get More", "B": "We're All Gonna Make It", "C": "We Are Getting Money In", "D": "Wait Are Gains Mine", "answer": "B", "cat": "CRYPTO"},
  {"q": "What does \"FUD\" stand for?", "A": "Funds Under Development", "B": "Fully Undervalued Dip", "C": "Fear, Uncertainty, Doubt", "D": "Fast Up Down", "answer": "C", "cat": "CRYPTO"},
  {"q": "Market cap is calculated as...", "A": "Holders x price", "B": "Liquidity x 2", "C": "Volume x price", "D": "Price x supply", "answer": "D", "cat": "CRYPTO"},
  {"q": "\"Paper hands\" describes someone who...", "A": "Holds forever", "B": "Provides liquidity", "C": "Sells at the first dip", "D": "Only buys ATH", "answer": "C", "cat": "CRYPTO"},
  {"q": "What does \"ATH\" mean?", "A": "After The Hype", "B": "At The Highs", "C": "All-Time High", "D": "Average Trade Height", "answer": "C", "cat": "CRYPTO"},
  {"q": "\"GM\" in a crypto chat means...", "A": "Good Morning", "B": "Good Money", "C": "Green Market", "D": "Get Money", "answer": "A", "cat": "CRYPTO"},
  {"q": "A \"memecoin\" is best described as...", "A": "A CBDC", "B": "A community/joke token", "C": "An NFT", "D": "A stablecoin", "answer": "B", "cat": "CRYPTO"},
  {"q": "\"Slippage\" refers to...", "A": "Price change between order and fill", "B": "A locked wallet", "C": "Gas fees", "D": "A failed tx", "answer": "A", "cat": "CRYPTO"},
  {"q": "An \"airdrop\" is...", "A": "Free token distribution to wallets", "B": "A hack", "C": "A sell-off", "D": "A bridge", "answer": "A", "cat": "CRYPTO"},
  {"q": "What is \"gas\" in crypto?", "A": "A token", "B": "A stablecoin", "C": "A transaction fee", "D": "A wallet", "answer": "C", "cat": "CRYPTO"},
  {"q": "A \"smart contract\" is...", "A": "A legal PDF", "B": "An exchange", "C": "Self-executing code on a blockchain", "D": "A hardware wallet", "answer": "C", "cat": "CRYPTO"},
  {"q": "What does NFT stand for?", "A": "New Finance Tech", "B": "Net Federal Tax", "C": "Node File Transfer", "D": "Non-Fungible Token", "answer": "D", "cat": "CRYPTO"},
  {"q": "A stablecoin is designed to...", "A": "Moon 100x", "B": "Hold a steady value (e.g. $1)", "C": "Burn daily", "D": "Stake itself", "answer": "B", "cat": "CRYPTO"},
  {"q": "USDC is pegged to the...", "A": "US Dollar", "B": "Gold", "C": "Euro", "D": "Bitcoin", "answer": "A", "cat": "CRYPTO"},
  {"q": "What does DeFi stand for?", "A": "Defined Finance", "B": "Decentralized Finance", "C": "Deferred Finance", "D": "Default Finance", "answer": "B", "cat": "CRYPTO"},
  {"q": "\"To the moon\" means...", "A": "A staking pool", "B": "A token burn", "C": "A rug pull", "D": "Price rising fast", "answer": "D", "cat": "CRYPTO"},
  {"q": "Being \"rekt\" means you...", "A": "Bridged", "B": "Won big", "C": "Lost badly", "D": "Staked", "answer": "C", "cat": "CRYPTO"},
  {"q": "\"NGMI\" stands for...", "A": "New Gains My Idea", "B": "Now Getting My Income", "C": "Not Gonna Make It", "D": "No Gas My Issue", "answer": "C", "cat": "CRYPTO"},
  {"q": "A \"degen\" is a...", "A": "Data node", "B": "Developer", "C": "Delegator", "D": "Degenerate trader/gambler", "answer": "D", "cat": "CRYPTO"},
  {"q": "\"Aping in\" means...", "A": "Bridging", "B": "Buying heavily and fast", "C": "Staking", "D": "Selling slowly", "answer": "B", "cat": "CRYPTO"},
  {"q": "A \"bag holder\" is someone who...", "A": "Runs an exchange", "B": "Holds a losing position", "C": "Provides liquidity", "D": "Mines Bitcoin", "answer": "B", "cat": "CRYPTO"},
  {"q": "To \"shill\" a coin means to...", "A": "Burn it", "B": "Aggressively promote it", "C": "Audit it", "D": "Short it", "answer": "B", "cat": "CRYPTO"},
  {"q": "A \"pump and dump\" is...", "A": "A hard fork", "B": "Locking liquidity", "C": "Staking rewards", "D": "Inflating price then selling", "answer": "D", "cat": "CRYPTO"},
  {"q": "\"Liquidity\" refers to...", "A": "Wallet balance", "B": "Gas fees", "C": "Funds available to trade against", "D": "Block time", "answer": "C", "cat": "CRYPTO"},
  {"q": "\"LP\" most commonly means...", "A": "Long Position", "B": "Liquidity Provider/Pool", "C": "Low Price", "D": "Ledger Proof", "answer": "B", "cat": "CRYPTO"},
  {"q": "\"TVL\" stands for...", "A": "Token Vesting Ledger", "B": "Trade Volume Limit", "C": "Total Volume Live", "D": "Total Value Locked", "answer": "D", "cat": "CRYPTO"},
  {"q": "A \"cold wallet\" is...", "A": "A burner token", "B": "An exchange account", "C": "A hot swap", "D": "Offline storage", "answer": "D", "cat": "CRYPTO"},
  {"q": "Your \"seed phrase\" is...", "A": "A staking reward", "B": "A public address", "C": "A gas setting", "D": "Your wallet recovery words", "answer": "D", "cat": "CRYPTO"},
  {"q": "You must NEVER share your...", "A": "Private key / seed phrase", "B": "ENS name", "C": "Username", "D": "Public address", "answer": "A", "cat": "CRYPTO"},
  {"q": "PoW stands for...", "A": "Proof of Work", "B": "Peg of Worth", "C": "Point of Withdrawal", "D": "Power of Wallets", "answer": "A", "cat": "CRYPTO"},
  {"q": "PoS stands for...", "A": "Proof of Sale", "B": "Proof of Stake", "C": "Peg of Stable", "D": "Price of Supply", "answer": "B", "cat": "CRYPTO"},
  {"q": "The Bitcoin \"halving\" cuts what in half?", "A": "The block reward", "B": "The fees", "C": "The supply", "D": "The price", "answer": "A", "cat": "CRYPTO"},
  {"q": "Dogecoin features which animal?", "A": "A Shiba Inu dog", "B": "A cat", "C": "A frog", "D": "A goat", "answer": "A", "cat": "CRYPTO"},
  {"q": "\"When lambo?\" really means...", "A": "When is the airdrop?", "B": "When does it unlock?", "C": "When is the burn?", "D": "When will I get rich?", "answer": "D", "cat": "CRYPTO"},
  {"q": "A CEX is a...", "A": "Crypto Escrow", "B": "Chain Extension", "C": "Coin Explorer", "D": "Centralized Exchange", "answer": "D", "cat": "CRYPTO"},
  {"q": "\"KYC\" stands for...", "A": "Known Yield Curve", "B": "Know Your Customer", "C": "Key Your Cache", "D": "Keep Your Coins", "answer": "B", "cat": "CRYPTO"},
  {"q": "\"Mainnet\" is the... ", "A": "Test network", "B": "Backup node", "C": "Mining pool", "D": "Live production network", "answer": "D", "cat": "CRYPTO"},
  {"q": "A \"bridge\" is used to...", "A": "Audit contracts", "B": "Lock staking", "C": "Move assets between chains", "D": "Burn tokens", "answer": "C", "cat": "CRYPTO"},
  {"q": "\"WETH\" is...", "A": "Weekly ETH", "B": "Western ETH", "C": "Wrapped ETH", "D": "Withdrawn ETH", "answer": "C", "cat": "CRYPTO"},
  {"q": "To \"burn\" tokens means to...", "A": "Permanently remove them", "B": "Stake them", "C": "Lock them 1 year", "D": "Sell them", "answer": "A", "cat": "CRYPTO"},
  {"q": "To \"mint\" a token means to...", "A": "Audit tokens", "B": "Create new tokens", "C": "Trade tokens", "D": "Delete tokens", "answer": "B", "cat": "CRYPTO"},
  {"q": "\"Gwei\" is a unit of...", "A": "Supply", "B": "Market cap", "C": "Gas price", "D": "Slippage", "answer": "C", "cat": "CRYPTO"},
  {"q": "A blockchain \"block\" contains...", "A": "One wallet", "B": "One token", "C": "A batch of transactions", "D": "The whole ledger twice", "answer": "C", "cat": "CRYPTO"},
  {"q": "A \"fork\" is a...", "A": "Gas token", "B": "Wallet type", "C": "Trading pair", "D": "Split in the blockchain", "answer": "D", "cat": "CRYPTO"},
  {"q": "The very first block is called the...", "A": "Genesis block", "B": "Alpha hash", "C": "Origin coin", "D": "Prime node", "answer": "A", "cat": "CRYPTO"},
  {"q": "\"ser\" in crypto slang means...", "A": "seller", "B": "sir", "C": "server", "D": "series", "answer": "B", "cat": "CRYPTO"},
  {"q": "\"fren\" means...", "A": "freeze", "B": "front-run", "C": "free NFT", "D": "friend", "answer": "D", "cat": "CRYPTO"},
  {"q": "A \"whitelist\" gives you...", "A": "A refund", "B": "A burn", "C": "Early/guaranteed access", "D": "Free gas", "answer": "C", "cat": "CRYPTO"},
  {"q": "\"Vaporware\" is a project that...", "A": "Is audited", "B": "Is a stablecoin", "C": "Is hyped but never ships", "D": "Ships early", "answer": "C", "cat": "CRYPTO"},
  {"q": "The smallest unit of Bitcoin is a...", "A": "Gwei", "B": "Satoshi", "C": "Bit", "D": "Wei", "answer": "B", "cat": "CRYPTO"},
  {"q": "The smallest unit of Ether is a...", "A": "Finney", "B": "Wei", "C": "Satoshi", "D": "Gwei", "answer": "B", "cat": "CRYPTO"},
  {"q": "An \"L1\" blockchain is a...", "A": "Wallet", "B": "Exchange", "C": "Rollup", "D": "Base layer (e.g. Ethereum)", "answer": "D", "cat": "CRYPTO"},
  {"q": "A \"rollup\" helps by...", "A": "Burning supply", "B": "Locking liquidity", "C": "Adding KYC", "D": "Scaling / cheaper transactions", "answer": "D", "cat": "CRYPTO"},
  {"q": "\"Front-running\" means...", "A": "Selling first", "B": "Buying the top", "C": "Locking LP", "D": "Jumping ahead of a pending trade", "answer": "D", "cat": "CRYPTO"},
  {"q": "A \"honeypot\" token lets you...", "A": "Buy but not sell", "B": "Stake forever", "C": "Sell but not buy", "D": "Bridge free", "answer": "A", "cat": "CRYPTO"},
  {"q": "\"Sats stacking\" means accumulating...", "A": "NFTs", "B": "Small amounts of Bitcoin", "C": "Gas", "D": "Stablecoins", "answer": "B", "cat": "CRYPTO"},
  {"q": "\"Probably nothing\" ironically means...", "A": "It's boring", "B": "Probably something big", "C": "It's over", "D": "It's a scam", "answer": "B", "cat": "CRYPTO"},
  {"q": "A token's \"circulating supply\" is...", "A": "Coins currently in the market", "B": "Burned coins", "C": "Max ever", "D": "Locked team coins", "answer": "A", "cat": "CRYPTO"},
  {"q": "\"Dumping\" means...", "A": "Selling a lot at once", "B": "Bridging", "C": "Buying the dip", "D": "Staking", "answer": "A", "cat": "CRYPTO"},
  {"q": "The Ethereum \"Merge\" switched it to...", "A": "A new coin", "B": "A sidechain", "C": "Proof of Stake", "D": "Proof of Work", "answer": "C", "cat": "CRYPTO"},
  {"q": "\"DYOR\" stands for...", "A": "Daily Yield Over Return", "B": "Drop Your Own Rug", "C": "Do Your Own Research", "D": "Don't Yield On Risk", "answer": "C", "cat": "CRYPTO"},
];
