// $STAG trivia question bank. Cards are pre-rendered at assets/trivia/tNN.jpg (NN = index+1).
export const TRIVIA = [
  {"q": "$STAG's mascot is a stag styled after which folk hero?", "A": "King Arthur", "B": "Robin Hood", "C": "William Tell", "D": "Zorro", "answer": "B", "cat": "STAG"},
  {"q": "Which chain did $STAG launch on?", "A": "Solana", "B": "Base", "C": "Robinhood Chain", "D": "Tron", "answer": "C", "cat": "STAG"},
  {"q": "Robinhood Chain is built on which L2 tech?", "A": "Optimism", "B": "zkSync", "C": "Polygon PoS", "D": "Arbitrum Orbit", "answer": "D", "cat": "STAG"},
  {"q": "$STAG's motto: \"Steal the pump, feed the ___\"", "A": "holders", "B": "whales", "C": "devs", "D": "bears", "answer": "A", "cat": "STAG"},
  {"q": "What is $STAG's total supply?", "A": "100 million", "B": "1 billion", "C": "21 million", "D": "1 trillion", "answer": "B", "cat": "STAG"},
  {"q": "What is the gas token on Robinhood Chain?", "A": "HOOD", "B": "SOL", "C": "ETH", "D": "MATIC", "answer": "C", "cat": "STAG"},
  {"q": "Which launchpad was $STAG created through?", "A": "Pump.fun", "B": "NOXA Fun", "C": "Raydium", "D": "LetsBonk", "answer": "B", "cat": "STAG"},
  {"q": "The @STAGZBOT can generate all of these EXCEPT:", "A": "PFPs", "B": "Scene images", "C": "Short videos", "D": "Your taxes", "answer": "D", "cat": "STAG"},
  {"q": "Where does the term \"HODL\" come from?", "A": "An acronym", "B": "A typo of 'hold'", "C": "A Greek word", "D": "Satoshi's blog", "answer": "B", "cat": "CRYPTO"},
  {"q": "Who is Bitcoin's pseudonymous creator?", "A": "Vitalik Buterin", "B": "Satoshi Nakamoto", "C": "Charlie Lee", "D": "Nick Szabo", "answer": "B", "cat": "CRYPTO"},
  {"q": "What is the max supply of Bitcoin?", "A": "21 million", "B": "100 million", "C": "Unlimited", "D": "1 billion", "answer": "A", "cat": "CRYPTO"},
  {"q": "\"Diamond hands\" means you...", "A": "Panic sell", "B": "Hold through volatility", "C": "Day trade", "D": "Short the market", "answer": "B", "cat": "CRYPTO"},
  {"q": "A \"rug pull\" is when...", "A": "Price 2x's", "B": "Devs drain the liquidity", "C": "A whale buys", "D": "The chart goes up", "answer": "B", "cat": "CRYPTO"},
  {"q": "What does DEX stand for?", "A": "Digital Exchange", "B": "Decentralized Exchange", "C": "Direct Exchange", "D": "Data Exchange", "answer": "B", "cat": "CRYPTO"},
  {"q": "In crypto, a \"whale\" is...", "A": "A scam token", "B": "A large holder", "C": "A dead coin", "D": "An exchange", "answer": "B", "cat": "CRYPTO"},
  {"q": "\"WAGMI\" stands for...", "A": "We Are Getting Money In", "B": "We're All Gonna Make It", "C": "Wait, Are Gains My Idea", "D": "Whales Always Get More", "answer": "B", "cat": "CRYPTO"},
  {"q": "What does \"FUD\" stand for?", "A": "Fear, Uncertainty, Doubt", "B": "Funds Under Development", "C": "Fast Up Down", "D": "Fully Undervalued Dip", "answer": "A", "cat": "CRYPTO"},
  {"q": "Market cap is calculated as...", "A": "Volume x price", "B": "Price x supply", "C": "Liquidity x 2", "D": "Holders x price", "answer": "B", "cat": "CRYPTO"},
  {"q": "\"Paper hands\" describes someone who...", "A": "Holds forever", "B": "Sells at the first dip", "C": "Only buys ATH", "D": "Provides liquidity", "answer": "B", "cat": "CRYPTO"},
  {"q": "What does \"ATH\" mean?", "A": "At The Highs", "B": "All-Time High", "C": "Average Trade Height", "D": "After The Hype", "answer": "B", "cat": "CRYPTO"},
  {"q": "\"GM\" in a crypto chat means...", "A": "Good Money", "B": "Good Morning", "C": "Green Market", "D": "Get Money", "answer": "B", "cat": "CRYPTO"},
  {"q": "A \"memecoin\" is best described as...", "A": "A stablecoin", "B": "A community/joke-driven token", "C": "A CBDC", "D": "An NFT", "answer": "B", "cat": "CRYPTO"},
  {"q": "\"Slippage\" refers to...", "A": "A failed tx", "B": "Price change between order and fill", "C": "Gas fees", "D": "A locked wallet", "answer": "B", "cat": "CRYPTO"},
  {"q": "An \"airdrop\" is...", "A": "A hack", "B": "Free token distribution to wallets", "C": "A sell-off", "D": "A bridge", "answer": "B", "cat": "CRYPTO"},
];
