// $STAG trivia question bank (85). Cards pre-rendered at assets/trivia/tNN.jpg (NN = index+1).
// Correct-answer letters are balanced ~22/21/21/21 across A/B/C/D.
export const TRIVIA = [
  {"q": "$STAG's mascot is a stag styled after which folk hero?", "A": "King Arthur", "B": "William Tell", "C": "Robin Hood", "D": "Zorro", "answer": "C", "cat": "STAG"},
  {"q": "Which chain did $STAG launch on?", "A": "Base", "B": "Tron", "C": "Robinhood Chain", "D": "Solana", "answer": "C", "cat": "STAG"},
  {"q": "Robinhood Chain is built on which L2 tech?", "A": "Polygon PoS", "B": "zkSync", "C": "Optimism", "D": "Arbitrum Orbit", "answer": "D", "cat": "STAG"},
  {"q": "$STAG's motto: \"Steal the pump, feed the ___\"", "A": "whales", "B": "bears", "C": "holders", "D": "devs", "answer": "C", "cat": "STAG"},
  {"q": "What is $STAG's total supply?", "A": "21 million", "B": "1 billion", "C": "1 trillion", "D": "100 million", "answer": "B", "cat": "STAG"},
  {"q": "What is the gas token on Robinhood Chain?", "A": "HOOD", "B": "SOL", "C": "ETH", "D": "MATIC", "answer": "C", "cat": "STAG"},
  {"q": "Which launchpad was $STAG created through?", "A": "NOXA Fun", "B": "LetsBonk", "C": "Raydium", "D": "Pump.fun", "answer": "A", "cat": "STAG"},
  {"q": "The @STAGZBOT can generate all of these EXCEPT:", "A": "PFPs", "B": "Short videos", "C": "Scene images", "D": "Your taxes", "answer": "D", "cat": "STAG"},
  {"q": "What is Robinhood Chain's chain ID?", "A": "4663", "B": "42161", "C": "8453", "D": "1", "answer": "A", "cat": "STAG"},
  {"q": "Robinhood is best known as a...", "A": "Social network", "B": "Ride app", "C": "Stock trading app", "D": "Search engine", "answer": "C", "cat": "STAG"},
  {"q": "Which @STAGZBOT command makes a video?", "A": "/pfp", "B": "/vid", "C": "/image", "D": "/buy", "answer": "B", "cat": "STAG"},
  {"q": "Hold how much $STAG to unlock 50% off credits?", "A": "100", "B": "10,000", "C": "1 billion", "D": "1,000,000", "answer": "D", "cat": "STAG"},
  {"q": "Robin Hood famously steals from the rich to give to the...", "A": "poor", "B": "king", "C": "sheriff", "D": "banks", "answer": "A", "cat": "STAG"},
  {"q": "What color glow is $STAG's brand?", "A": "Green", "B": "Gold", "C": "Purple", "D": "Red", "answer": "A", "cat": "STAG"},
  {"q": "Robinhood Chain transactions are cheap because it's a...", "A": "Testnet", "B": "Sidechain DB", "C": "Layer 1", "D": "Layer 2", "answer": "D", "cat": "STAG"},
  {"q": "$STAG's weekly trivia champ wins a prize in...", "A": "NFTs", "B": "AI credits", "C": "Gift cards", "D": "Cash", "answer": "B", "cat": "STAG"},
  {"q": "Where does the term \"HODL\" come from?", "A": "A Greek word", "B": "Satoshi's blog", "C": "An acronym", "D": "A typo of 'hold'", "answer": "D", "cat": "CRYPTO"},
  {"q": "Who is Bitcoin's pseudonymous creator?", "A": "Charlie Lee", "B": "Vitalik Buterin", "C": "Nick Szabo", "D": "Satoshi Nakamoto", "answer": "D", "cat": "CRYPTO"},
  {"q": "What is the max supply of Bitcoin?", "A": "21 million", "B": "100 million", "C": "Unlimited", "D": "1 billion", "answer": "A", "cat": "CRYPTO"},
  {"q": "Who created Ethereum?", "A": "Vitalik Buterin", "B": "Gavin Wood", "C": "Satoshi Nakamoto", "D": "CZ", "answer": "A", "cat": "CRYPTO"},
  {"q": "\"Diamond hands\" means you...", "A": "Panic sell", "B": "Short the market", "C": "Day trade", "D": "Hold through volatility", "answer": "D", "cat": "CRYPTO"},
  {"q": "A \"rug pull\" is when...", "A": "Devs drain the liquidity", "B": "Price 2x's", "C": "A whale buys", "D": "The chart goes up", "answer": "A", "cat": "CRYPTO"},
  {"q": "What does DEX stand for?", "A": "Digital Exchange", "B": "Decentralized Exchange", "C": "Direct Exchange", "D": "Data Exchange", "answer": "B", "cat": "CRYPTO"},
  {"q": "In crypto, a \"whale\" is...", "A": "A dead coin", "B": "A scam token", "C": "A large holder", "D": "An exchange", "answer": "C", "cat": "CRYPTO"},
  {"q": "\"WAGMI\" stands for...", "A": "We're All Gonna Make It", "B": "Whales Always Get More", "C": "We Are Getting Money In", "D": "Wait Are Gains Mine", "answer": "A", "cat": "CRYPTO"},
  {"q": "What does \"FUD\" stand for?", "A": "Funds Under Development", "B": "Fast Up Down", "C": "Fully Undervalued Dip", "D": "Fear, Uncertainty, Doubt", "answer": "D", "cat": "CRYPTO"},
  {"q": "Market cap is calculated as...", "A": "Volume x price", "B": "Price x supply", "C": "Liquidity x 2", "D": "Holders x price", "answer": "B", "cat": "CRYPTO"},
  {"q": "\"Paper hands\" describes someone who...", "A": "Sells at the first dip", "B": "Provides liquidity", "C": "Only buys ATH", "D": "Holds forever", "answer": "A", "cat": "CRYPTO"},
  {"q": "What does \"ATH\" mean?", "A": "After The Hype", "B": "All-Time High", "C": "At The Highs", "D": "Average Trade Height", "answer": "B", "cat": "CRYPTO"},
  {"q": "\"GM\" in a crypto chat means...", "A": "Get Money", "B": "Good Money", "C": "Green Market", "D": "Good Morning", "answer": "D", "cat": "CRYPTO"},
  {"q": "A \"memecoin\" is best described as...", "A": "A community/joke token", "B": "A stablecoin", "C": "A CBDC", "D": "An NFT", "answer": "A", "cat": "CRYPTO"},
  {"q": "\"Slippage\" refers to...", "A": "Gas fees", "B": "A failed tx", "C": "A locked wallet", "D": "Price change between order and fill", "answer": "D", "cat": "CRYPTO"},
  {"q": "An \"airdrop\" is...", "A": "A sell-off", "B": "A hack", "C": "Free token distribution to wallets", "D": "A bridge", "answer": "C", "cat": "CRYPTO"},
  {"q": "What is \"gas\" in crypto?", "A": "A token", "B": "A transaction fee", "C": "A wallet", "D": "A stablecoin", "answer": "B", "cat": "CRYPTO"},
  {"q": "A \"smart contract\" is...", "A": "An exchange", "B": "A legal PDF", "C": "Self-executing code on a blockchain", "D": "A hardware wallet", "answer": "C", "cat": "CRYPTO"},
  {"q": "What does NFT stand for?", "A": "Node File Transfer", "B": "Net Federal Tax", "C": "New Finance Tech", "D": "Non-Fungible Token", "answer": "D", "cat": "CRYPTO"},
  {"q": "A stablecoin is designed to...", "A": "Burn daily", "B": "Stake itself", "C": "Hold a steady value (e.g. $1)", "D": "Moon 100x", "answer": "C", "cat": "CRYPTO"},
  {"q": "USDC is pegged to the...", "A": "US Dollar", "B": "Euro", "C": "Gold", "D": "Bitcoin", "answer": "A", "cat": "CRYPTO"},
  {"q": "What does DeFi stand for?", "A": "Deferred Finance", "B": "Defined Finance", "C": "Decentralized Finance", "D": "Default Finance", "answer": "C", "cat": "CRYPTO"},
  {"q": "\"To the moon\" means...", "A": "Price rising fast", "B": "A staking pool", "C": "A rug pull", "D": "A token burn", "answer": "A", "cat": "CRYPTO"},
  {"q": "Being \"rekt\" means you...", "A": "Bridged", "B": "Won big", "C": "Lost badly", "D": "Staked", "answer": "C", "cat": "CRYPTO"},
  {"q": "\"NGMI\" stands for...", "A": "New Gains My Idea", "B": "No Gas My Issue", "C": "Not Gonna Make It", "D": "Now Getting My Income", "answer": "C", "cat": "CRYPTO"},
  {"q": "A \"degen\" is a...", "A": "Delegator", "B": "Developer", "C": "Degenerate trader/gambler", "D": "Data node", "answer": "C", "cat": "CRYPTO"},
  {"q": "\"Aping in\" means...", "A": "Bridging", "B": "Staking", "C": "Buying heavily and fast", "D": "Selling slowly", "answer": "C", "cat": "CRYPTO"},
  {"q": "A \"bag holder\" is someone who...", "A": "Holds a losing position", "B": "Mines Bitcoin", "C": "Provides liquidity", "D": "Runs an exchange", "answer": "A", "cat": "CRYPTO"},
  {"q": "To \"shill\" a coin means to...", "A": "Audit it", "B": "Aggressively promote it", "C": "Burn it", "D": "Short it", "answer": "B", "cat": "CRYPTO"},
  {"q": "A \"pump and dump\" is...", "A": "Staking rewards", "B": "Locking liquidity", "C": "Inflating price then selling", "D": "A hard fork", "answer": "C", "cat": "CRYPTO"},
  {"q": "\"Liquidity\" refers to...", "A": "Funds available to trade against", "B": "Wallet balance", "C": "Block time", "D": "Gas fees", "answer": "A", "cat": "CRYPTO"},
  {"q": "\"LP\" most commonly means...", "A": "Ledger Proof", "B": "Long Position", "C": "Low Price", "D": "Liquidity Provider/Pool", "answer": "D", "cat": "CRYPTO"},
  {"q": "\"TVL\" stands for...", "A": "Token Vesting Ledger", "B": "Total Value Locked", "C": "Trade Volume Limit", "D": "Total Volume Live", "answer": "B", "cat": "CRYPTO"},
  {"q": "A \"cold wallet\" is...", "A": "An exchange account", "B": "Offline storage", "C": "A burner token", "D": "A hot swap", "answer": "B", "cat": "CRYPTO"},
  {"q": "Your \"seed phrase\" is...", "A": "A staking reward", "B": "Your wallet recovery words", "C": "A public address", "D": "A gas setting", "answer": "B", "cat": "CRYPTO"},
  {"q": "You must NEVER share your...", "A": "Username", "B": "Private key / seed phrase", "C": "ENS name", "D": "Public address", "answer": "B", "cat": "CRYPTO"},
  {"q": "PoW stands for...", "A": "Peg of Worth", "B": "Point of Withdrawal", "C": "Proof of Work", "D": "Power of Wallets", "answer": "C", "cat": "CRYPTO"},
  {"q": "PoS stands for...", "A": "Proof of Stake", "B": "Proof of Sale", "C": "Price of Supply", "D": "Peg of Stable", "answer": "A", "cat": "CRYPTO"},
  {"q": "The Bitcoin \"halving\" cuts what in half?", "A": "The price", "B": "The supply", "C": "The block reward", "D": "The fees", "answer": "C", "cat": "CRYPTO"},
  {"q": "Dogecoin features which animal?", "A": "A Shiba Inu dog", "B": "A frog", "C": "A cat", "D": "A goat", "answer": "A", "cat": "CRYPTO"},
  {"q": "\"When lambo?\" really means...", "A": "When will I get rich?", "B": "When does it unlock?", "C": "When is the burn?", "D": "When is the airdrop?", "answer": "A", "cat": "CRYPTO"},
  {"q": "A CEX is a...", "A": "Centralized Exchange", "B": "Crypto Escrow", "C": "Coin Explorer", "D": "Chain Extension", "answer": "A", "cat": "CRYPTO"},
  {"q": "\"KYC\" stands for...", "A": "Key Your Cache", "B": "Known Yield Curve", "C": "Keep Your Coins", "D": "Know Your Customer", "answer": "D", "cat": "CRYPTO"},
  {"q": "\"Mainnet\" is the... ", "A": "Mining pool", "B": "Backup node", "C": "Test network", "D": "Live production network", "answer": "D", "cat": "CRYPTO"},
  {"q": "A \"bridge\" is used to...", "A": "Lock staking", "B": "Audit contracts", "C": "Move assets between chains", "D": "Burn tokens", "answer": "C", "cat": "CRYPTO"},
  {"q": "\"WETH\" is...", "A": "Weekly ETH", "B": "Wrapped ETH", "C": "Western ETH", "D": "Withdrawn ETH", "answer": "B", "cat": "CRYPTO"},
  {"q": "To \"burn\" tokens means to...", "A": "Sell them", "B": "Permanently remove them", "C": "Lock them 1 year", "D": "Stake them", "answer": "B", "cat": "CRYPTO"},
  {"q": "To \"mint\" a token means to...", "A": "Delete tokens", "B": "Trade tokens", "C": "Audit tokens", "D": "Create new tokens", "answer": "D", "cat": "CRYPTO"},
  {"q": "\"Gwei\" is a unit of...", "A": "Slippage", "B": "Gas price", "C": "Supply", "D": "Market cap", "answer": "B", "cat": "CRYPTO"},
  {"q": "A blockchain \"block\" contains...", "A": "The whole ledger twice", "B": "A batch of transactions", "C": "One wallet", "D": "One token", "answer": "B", "cat": "CRYPTO"},
  {"q": "A \"fork\" is a...", "A": "Split in the blockchain", "B": "Trading pair", "C": "Gas token", "D": "Wallet type", "answer": "A", "cat": "CRYPTO"},
  {"q": "The very first block is called the...", "A": "Genesis block", "B": "Origin coin", "C": "Prime node", "D": "Alpha hash", "answer": "A", "cat": "CRYPTO"},
  {"q": "\"ser\" in crypto slang means...", "A": "seller", "B": "sir", "C": "series", "D": "server", "answer": "B", "cat": "CRYPTO"},
  {"q": "\"fren\" means...", "A": "front-run", "B": "free NFT", "C": "freeze", "D": "friend", "answer": "D", "cat": "CRYPTO"},
  {"q": "A \"whitelist\" gives you...", "A": "Free gas", "B": "A refund", "C": "A burn", "D": "Early/guaranteed access", "answer": "D", "cat": "CRYPTO"},
  {"q": "\"Vaporware\" is a project that...", "A": "Is audited", "B": "Ships early", "C": "Is hyped but never ships", "D": "Is a stablecoin", "answer": "C", "cat": "CRYPTO"},
  {"q": "The smallest unit of Bitcoin is a...", "A": "Satoshi", "B": "Bit", "C": "Gwei", "D": "Wei", "answer": "A", "cat": "CRYPTO"},
  {"q": "The smallest unit of Ether is a...", "A": "Satoshi", "B": "Gwei", "C": "Wei", "D": "Finney", "answer": "C", "cat": "CRYPTO"},
  {"q": "An \"L1\" blockchain is a...", "A": "Wallet", "B": "Exchange", "C": "Rollup", "D": "Base layer (e.g. Ethereum)", "answer": "D", "cat": "CRYPTO"},
  {"q": "A \"rollup\" helps by...", "A": "Adding KYC", "B": "Scaling / cheaper transactions", "C": "Locking liquidity", "D": "Burning supply", "answer": "B", "cat": "CRYPTO"},
  {"q": "\"Front-running\" means...", "A": "Selling first", "B": "Jumping ahead of a pending trade", "C": "Buying the top", "D": "Locking LP", "answer": "B", "cat": "CRYPTO"},
  {"q": "A \"honeypot\" token lets you...", "A": "Bridge free", "B": "Buy but not sell", "C": "Stake forever", "D": "Sell but not buy", "answer": "B", "cat": "CRYPTO"},
  {"q": "\"Sats stacking\" means accumulating...", "A": "Small amounts of Bitcoin", "B": "Gas", "C": "NFTs", "D": "Stablecoins", "answer": "A", "cat": "CRYPTO"},
  {"q": "\"Probably nothing\" ironically means...", "A": "It's over", "B": "It's a scam", "C": "It's boring", "D": "Probably something big", "answer": "D", "cat": "CRYPTO"},
  {"q": "A token's \"circulating supply\" is...", "A": "Locked team coins", "B": "Burned coins", "C": "Max ever", "D": "Coins currently in the market", "answer": "D", "cat": "CRYPTO"},
  {"q": "\"Dumping\" means...", "A": "Staking", "B": "Buying the dip", "C": "Bridging", "D": "Selling a lot at once", "answer": "D", "cat": "CRYPTO"},
  {"q": "The Ethereum \"Merge\" switched it to...", "A": "A new coin", "B": "A sidechain", "C": "Proof of Stake", "D": "Proof of Work", "answer": "C", "cat": "CRYPTO"},
  {"q": "\"DYOR\" stands for...", "A": "Drop Your Own Rug", "B": "Do Your Own Research", "C": "Daily Yield Over Return", "D": "Don't Yield On Risk", "answer": "B", "cat": "CRYPTO"},
];
