// $STAGWIFHOOD Telegram bot — FREE PFP generator (Vercel webhook).
//
// Users run /pfp IN THE GROUP (not DM) and get a unique, on-character $STAG PFP
// back, generated by Venice image/edit off the approved character art so every
// result keeps his identity (antlers, green hood, glowing eyes) but a NEW pose.
// A single shared 4,000-credit pool (~$5) funds the free drop; when it's gone,
// the bot closes the drop and points people at the token. /pfpcredits shows the
// live pool.
//
// Commands:
//   /pfp [optional style]  -> generate a PFP, reply in-chat (group)
//   /pfpcredits            -> show credits used / remaining
//   /start /help           -> how it works
//
// Required Vercel env (this is a PUBLIC repo — only NAMES live here, never values):
//   STAG_BOT_TOKEN     Telegram bot token for @STAGZBOT
//   STAG_VENICE_KEY    Venice *inference* key (NOT the admin key)   [or VENICE_KEY]
//   DATABASE_URL       Neon Postgres (shared with the other endpoints)
// Optional:
//   STAG_BOT_SECRET    Telegram webhook secret-token header (recommended)
//   STAG_PFP_MODEL     Venice edit model. default nano-banana-pro-edit
//   STAG_PFP_COST      credits charged per PFP. default 144  (=$0.18 at 4000cr≈$5)
//   STAG_PFP_BUDGET    total credit pool. default 4000  (≈ $5)
//   STAG_PFP_COOLDOWN  seconds a single user must wait between PFPs. default 45
//                      (anti-drain pacing, NOT a per-user cap — one bot could
//                       otherwise burn the whole pool in seconds)
//
// SECURITY: never mentions catboy. The Venice key MUST be an inference key.
// No secrets are committed — everything sensitive is a Vercel env var.

import { neon } from "@neondatabase/serverless";
import { STAG_REF_B64 } from "./_stagref.js";

const CONN = (process.env.DATABASE_URL || process.env.POSTGRES_URL || "").trim();
const TOKEN = (process.env.STAG_BOT_TOKEN || "").trim();
const HOOK_SECRET = (process.env.STAG_BOT_SECRET || "").trim();
const MODEL = (process.env.STAG_PFP_MODEL || "nano-banana-pro-edit").trim();
const COST = parseInt(process.env.STAG_PFP_COST || "144", 10);      // credits / PFP
const BUDGET = parseInt(process.env.STAG_PFP_BUDGET || "4000", 10); // total pool
const PER_USER = parseInt(process.env.STAG_PFP_PER_USER || "1", 10);// free PFPs per person
const COOLDOWN = parseInt(process.env.STAG_PFP_COOLDOWN || "45", 10) * 1000;
// Phase 2 (flip on when the free pool is gone): gate /pfp to verified holders.
// Verification is a separate build (see HOLDER-REWARDS-BRIEF.md) — until it exists
// this stays "0" (open free-for-all, 1 each) and the bot just closes when tapped out.
const HOLDER_ONLY = process.env.STAG_PFP_HOLDER_ONLY === "1";
const TG = (m) => `https://api.telegram.org/bot${TOKEN}/${m}`;

export const config = { maxDuration: 60 };

// ── Venice inference key resolver (prefix words are PART of the key) ────────────
const VK_PREFIX = "VENICE_INFERENCE_KEY_";
function veniceKey() {
  const direct = process.env.STAG_VENICE_KEY || process.env.VENICE_KEY ||
                 process.env.VENICE_API_KEY || process.env.VENICE_INFERENCE_KEY;
  if (direct && direct.startsWith(VK_PREFIX)) return direct;
  const venice = Object.entries(process.env).filter(([n, v]) => /^VENICE/i.test(n) && v);
  for (const [, v] of venice) if (v.startsWith(VK_PREFIX)) return v;
  for (const [n, v] of venice) if (/^VENICE_INFERENCE_KEY_*$/i.test(n)) return VK_PREFIX + v;
  return direct || (venice[0] && venice[0][1]) || "";
}

// ── Pose variety: each PFP gets a different pose/scene so they're never twins ───
const POSES = [
  "drawing a glowing emerald arrow on a longbow, fierce focus",
  "arms crossed, hood up, smirking confidently",
  "mid-leap firing an arrow, cape flaring, motion energy",
  "regal three-quarter portrait, chin up, commanding",
  "perched on a neon-lit rooftop overlooking a cyber-forest city at dusk",
  "battle-worn close-up, one eye glowing brighter, embers drifting",
  "raising a fist of green flame, triumphant",
  "cloaked in shadow with only the antlers and glowing eyes catching light",
  "leaning on the longbow, relaxed but dangerous, faint grin",
  "war-cry mid-shout, antlers wreathed in green lightning",
  "stealthy crouch in emerald mist, arrow nocked",
  "heroic hero-shot, wind in the cloak, sunrise-green backlight",
  "holding a glowing $STAG coin, sly collector's grin",
  "storm brewing behind him, rain-slick armor, eyes ablaze",
  "sitting on a throne of antlers and vines, king of the forest",
  "back-to-back silhouette turn, glancing over the shoulder",
];
const STYLE_LOCK =
  " CRITICAL: match the reference art style EXACTLY — dark cinematic digital painting," +
  " gritty realistic dark-fantasy, dramatic moody lighting, intense neon-green glow," +
  " cyber-forest vibe, ultra detailed, epic and premium. NOT flat cartoon, NOT clean" +
  " vector. Keep his identity: large antlers, green Robin-Hood hood, glowing green eyes," +
  " muscular build. Head-and-shoulders square profile picture, centered, no text, no watermark.";

const BANNED = /\b(nude|naked|nsfw|sex|sexual|porn|explicit|hentai|nipple|genital|underage|child|loli|shota|rape|gore|catboy)\b/i;

// ── Telegram helpers ───────────────────────────────────────────────────────────
async function tg(method, payload) {
  try {
    const r = await fetch(TG(method), {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    return await r.json().catch(() => ({}));
  } catch { return {}; }
}
async function sendPhoto(chatId, pngBuf, caption, replyTo) {
  const fd = new FormData();
  fd.append("chat_id", String(chatId));
  if (caption) fd.append("caption", caption);
  if (replyTo) fd.append("reply_to_message_id", String(replyTo));
  fd.append("photo", new Blob([pngBuf], { type: "image/png" }), "stag.png");
  try {
    const r = await fetch(TG("sendPhoto"), { method: "POST", body: fd });
    return await r.json().catch(() => ({}));
  } catch { return {}; }
}

// ── Venice image/edit → raw PNG bytes ──────────────────────────────────────────
async function generate(prompt) {
  const key = veniceKey();
  if (!key) throw new Error("venice_not_configured");
  const r = await fetch("https://api.venice.ai/api/v1/image/edit", {
    method: "POST",
    headers: { Authorization: "Bearer " + key, "Content-Type": "application/json" },
    body: JSON.stringify({ model: MODEL, prompt, image: STAG_REF_B64 }),
  });
  const buf = Buffer.from(await r.arrayBuffer());
  // Success = raw PNG; failure = a JSON error body.
  if (buf.length > 8 && buf[0] === 0x89 && buf[1] === 0x50 && buf[2] === 0x4e && buf[3] === 0x47) return buf;
  let msg = "venice_failed_" + r.status;
  try { const j = JSON.parse(buf.toString("utf8")); msg = (j && (j.error || j.message)) || msg; } catch {}
  throw new Error(msg);
}

// ── DB: pool + cooldown + update dedupe ────────────────────────────────────────
async function ensure(s) {
  await s`CREATE TABLE IF NOT EXISTS stag_pfp_pool (id INT PRIMARY KEY, used INT NOT NULL DEFAULT 0)`;
  await s`INSERT INTO stag_pfp_pool (id, used) VALUES (1, 0) ON CONFLICT (id) DO NOTHING`;
  await s`CREATE TABLE IF NOT EXISTS stag_pfp_log (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, tid TEXT, uname TEXT, credits INT, created_at TIMESTAMPTZ DEFAULT now())`;
  await s`CREATE TABLE IF NOT EXISTS stag_pfp_cool (tid TEXT PRIMARY KEY, last_at TIMESTAMPTZ DEFAULT now())`;
  await s`CREATE TABLE IF NOT EXISTS stag_pfp_seen (uid BIGINT PRIMARY KEY, at TIMESTAMPTZ DEFAULT now())`;
  // Phase 2: filled by the (future) holder-verify flow — tid -> proven wallet holding ≥1M $STAG.
  await s`CREATE TABLE IF NOT EXISTS stag_verified (tid TEXT PRIMARY KEY, wallet TEXT, at TIMESTAMPTZ DEFAULT now())`;
}
async function isVerifiedHolder(s, tid) {
  const r = await s`SELECT 1 FROM stag_verified WHERE tid = ${tid}`;
  return r.length > 0;
}
// Atomically reserve COST from the pool; null if the drop is tapped out.
async function reserve(s) {
  const rows = await s`UPDATE stag_pfp_pool SET used = used + ${COST}
                       WHERE id = 1 AND used + ${COST} <= ${BUDGET} RETURNING used`;
  return rows.length ? Number(rows[0].used) : null;
}
async function refund(s) {
  await s`UPDATE stag_pfp_pool SET used = GREATEST(0, used - ${COST}) WHERE id = 1`;
}
async function poolUsed(s) {
  const r = await s`SELECT used FROM stag_pfp_pool WHERE id = 1`;
  return r.length ? Number(r[0].used) : 0;
}

const OUT_OF_CREDITS =
  "🎯 The free $STAGWIFHOOD PFP drop is *tapped out* — the whole pool got minted, antlers up. 🦌\n\n" +
  "Grab $STAG and stay locked in — bigger drops coming. 🏹💚";

// ── Main webhook ───────────────────────────────────────────────────────────────
export default async function handler(req, res) {
  // Telegram must always get a fast 200 or it retries; we do the work then 200.
  if (req.method !== "POST") { res.setHeader("Allow", "POST"); return res.status(405).end(); }
  if (HOOK_SECRET && req.headers["x-telegram-bot-api-secret-token"] !== HOOK_SECRET)
    return res.status(401).end();
  if (!TOKEN || !CONN) return res.status(200).json({ ok: false, error: "not_configured" });

  const update = typeof req.body === "string" ? JSON.parse(req.body || "{}") : (req.body || {});
  const msg = update.message || update.edited_message;
  const text = (msg && msg.text) || "";
  if (!msg || !text.startsWith("/")) return res.status(200).json({ ok: true });

  // Normalize command (strip @BotName), keep the rest as the style prompt.
  const sp = text.trim().indexOf(" ");
  let cmd = (sp === -1 ? text.trim() : text.slice(0, sp)).toLowerCase();
  cmd = cmd.split("@")[0];
  const style = sp === -1 ? "" : text.slice(sp + 1).trim().slice(0, 200);
  const chatId = msg.chat.id;
  const replyTo = msg.message_id;
  const tid = String(msg.from && msg.from.id || "");
  const uname = (msg.from && (msg.from.username ? "@" + msg.from.username : msg.from.first_name)) || "stag";

  const s = neon(CONN);
  try {
    await ensure(s);

    // Dedupe Telegram retries of the same update.
    if (update.update_id != null) {
      const seen = await s`INSERT INTO stag_pfp_seen (uid) VALUES (${update.update_id}) ON CONFLICT (uid) DO NOTHING RETURNING uid`;
      if (!seen.length) return res.status(200).json({ ok: true, dup: true });
    }

    if (cmd === "/start" || cmd === "/help" || cmd === "/pfphelp") {
      await tg("sendMessage", { chat_id: chatId, reply_to_message_id: replyTo, parse_mode: "Markdown",
        text: "🏹 *$STAGWIFHOOD free PFP generator*\n\n" +
              "• `/pfp` — mint yourself a unique $STAG profile pic (right here in chat)\n" +
              "• `/pfp cyber samurai` — add a style/theme and I'll work it in\n" +
              "• `/pfpcredits` — see how much of the free pool is left\n\n" +
              "*One free each* while the pool lasts — on-character, fresh pose every time.\n" +
              "Hold *1M $STAG* to keep generating after the free drop runs dry. 💚🦌" });
      return res.status(200).json({ ok: true });
    }

    if (cmd === "/pfpcredits") {
      const used = await poolUsed(s);
      const left = Math.max(0, BUDGET - used);
      const pfpsLeft = Math.floor(left / COST);
      await tg("sendMessage", { chat_id: chatId, reply_to_message_id: replyTo, parse_mode: "Markdown",
        text: `🎯 *$STAG PFP pool*\n\nUsed: *${used} / ${BUDGET}* credits\nRemaining: *${left}* (~${pfpsLeft} more free PFPs)` });
      return res.status(200).json({ ok: true });
    }

    if (cmd !== "/pfp") return res.status(200).json({ ok: true }); // ignore other commands

    // ---- /pfp ----
    if (style && BANNED.test(style)) {
      await tg("sendMessage", { chat_id: chatId, reply_to_message_id: replyTo,
        text: "🚫 Keep it clean, ranger. Try a different style." });
      return res.status(200).json({ ok: true });
    }

    // Phase 2: once the free pool is done, only verified 1M+ $STAG holders may generate.
    if (HOLDER_ONLY && !(await isVerifiedHolder(s, tid))) {
      await tg("sendMessage", { chat_id: chatId, reply_to_message_id: replyTo, parse_mode: "Markdown",
        text: "🔒 The free drop is over — the generator is now *holders only*.\n\n" +
              "Verify you hold *1M+ $STAG* to keep minting PFPs. (Ask an admin / see pinned for how.) 🏹💚" });
      return res.status(200).json({ ok: true, holderGated: true });
    }

    // One free PFP per person (Phase 1). Concurrent double-taps are absorbed by the cooldown.
    if (PER_USER > 0) {
      const mine = await s`SELECT COUNT(*)::int AS n FROM stag_pfp_log WHERE tid = ${tid}`;
      if (Number(mine[0].n) >= PER_USER) {
        await tg("sendMessage", { chat_id: chatId, reply_to_message_id: replyTo, parse_mode: "Markdown",
          text: "🦌 You already minted your free $STAG PFP, ranger. One each while the free drop lasts.\n\n" +
                "Hold *1M $STAG* and you'll keep generating after the free pool runs dry. 🏹💚" });
        return res.status(200).json({ ok: true, alreadyGot: true });
      }
    }

    // Cooldown (anti-drain pacing).
    if (COOLDOWN > 0) {
      const cr = await s`SELECT last_at FROM stag_pfp_cool WHERE tid = ${tid}`;
      if (cr.length) {
        const wait = COOLDOWN - (Date.now() - new Date(cr[0].last_at).getTime());
        if (wait > 0) {
          await tg("sendMessage", { chat_id: chatId, reply_to_message_id: replyTo,
            text: `⏳ Easy, ranger — one more in ${Math.ceil(wait / 1000)}s.` });
          return res.status(200).json({ ok: true });
        }
      }
    }

    // Reserve credits BEFORE generating so concurrent calls can't overspend.
    const usedAfter = await reserve(s);
    if (usedAfter == null) {
      await tg("sendMessage", { chat_id: chatId, reply_to_message_id: replyTo, parse_mode: "Markdown", text: OUT_OF_CREDITS });
      return res.status(200).json({ ok: true, tappedOut: true });
    }
    await s`INSERT INTO stag_pfp_cool (tid, last_at) VALUES (${tid}, now()) ON CONFLICT (tid) DO UPDATE SET last_at = now()`;

    await tg("sendChatAction", { chat_id: chatId, action: "upload_photo" });
    await tg("sendMessage", { chat_id: chatId, reply_to_message_id: replyTo, text: "🎨 Conjuring your $STAG… give me a few seconds. 🏹" });

    // Vary the pose by user + current pool position so no two are twins.
    let seed = 0; for (const c of tid) seed = (seed * 31 + c.charCodeAt(0)) >>> 0;
    const pose = POSES[(seed + Math.floor(usedAfter / COST)) % POSES.length];
    const prompt = `Head-and-shoulders profile-picture portrait of THIS exact character. New pose/scene: ${pose}.` +
      (style ? ` Also work in this theme: ${style}.` : "") + STYLE_LOCK;

    try {
      const png = await generate(prompt);
      await sendPhoto(chatId, png,
        `🦌 ${uname}, your $STAGWIFHOOD is minted. Set it as your PFP. 🏹💚\nOne free each • /pfpcredits to see the pool`,
        replyTo);
      await s`INSERT INTO stag_pfp_log (tid, uname, credits) VALUES (${tid}, ${uname}, ${COST})`;
      return res.status(200).json({ ok: true });
    } catch (e) {
      await refund(s); // generation failed → give the credits back to the pool
      await tg("sendMessage", { chat_id: chatId, reply_to_message_id: replyTo,
        text: "⚠️ The forge hiccuped — no credits spent. Hit /pfp to try again." });
      return res.status(200).json({ ok: false, error: String((e && e.message) || e) });
    }
  } catch (e) {
    return res.status(200).json({ ok: false, error: String((e && e.message) || e) });
  }
}
